### ISSUE TITLE
Ability to send Message Attributes

### ISSUE THREAD

**Issue by cdimitroulas** [scottjbarr/sqsmv#1]
Hey there,

Super cool library idea - this is a really useful little cli tool :)

Just wanted to ask about sending Message Attributes across because I noticed that in the code (btw I am not very knowledgable in golang) you only specify the `Body` and the `QueueUrl` when sending to SQS. Would it be easy to also send through the MessageAttributes property from the original message if it exists?

I can try and implement this if you like (would be good practice for my go!)

**Comment by cdimitroulas** [comment]
Jumped the gun and made a PR here! #2

**Comment by scottjbarr** [comment]
Glad you find the package useful.

Thanks for the PR @cdimitroulas
