### ISSUE TITLE
Build failing with golint import

### ISSUE THREAD

**Issue by sbrandtb** [scottjbarr/sqsmv#10]
When building locally, I get:

```
 $ make
rm -rf build dist
go get golang.org/x/tools/cmd/goimports
go get github.com/golang/lint/golint
can't load package: package github.com/golang/lint/golint: code in directory /home/sebastian/go/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"
Makefile:25: recipe for target 'tools' failed
make: *** [tools] Error 1
```

Short googling leads to [this issue](https://github.com/golang/lint/issues/415). I'm a Go beginner and cannot make heads or tails of it. Is it a version conflict?

**Comment by scottjbarr** [comment]
Hi @sbrandtb 

Good pickup. It looks like the official path has changed. 

I've updated the `tools` target in the Makefile with 56eb101.

Let me know if that is good for you.

**Comment by sbrandtb** [comment]
@scottjbarr Thanks, works like a charm now :)

I only had to add `~/go/bin` to `$PATH`, but I guess that's a general Go thing and doesn't need to be mentioned in your readme
