### ISSUE TITLE
Only consider the job done when receiving 0 messages more than once

### ISSUE THREAD

**Issue by joelittlejohn** [scottjbarr/sqsmv#15]
I have an SQS queue with a few thousand messages on it. I'm trying to move these messages to another queue, but sqsmv keeps stopping and saying it's done. I'm having to run sqsmv over and over again to move all messages. All the messages are visible and ready to be consumed.

From what I can tell, `client.ReceiveMessage` seems to return 10, 5 or 0 messages, even when the queue has 1000s of messages on it.

I can't think of any better way for sqsmv to work out that the work is complete. To improve this, could sqsmv only stop when it's received 0 messages twice or three times in a row?

**Comment by scottjbarr** [comment]
Interesting, I haven't seen a zero count returned when the queue still has messages. It definitely returns a variable number of messages, that it normal behaviour.

I'm happy to accept a PR that checks for multiple consecutive zero counts before exiting.
