### ISSUE TITLE
The build is failing due to an extraneous ";" on line 65 of main.go

### ISSUE THREAD

**Issue by hayu-gpsw** [scottjbarr/sqsmv#19]
The build is broken, with the latest go 1.12.7. It can be fixed by removing the extra ";" on line 65 of main.go.

65     lastMessageCount = len(resp.Messages);

$ make all
rm -rf build dist
go get golang.org/x/tools/cmd/goimports
go get golang.org/x/lint/golint
ret=0 && test -z "$(golint . | tee /dev/stderr)" || ret=1 ; exit $ret
go vet
ret=0 && test -z "$(goimports -l . | tee /dev/stderr)" || ret=1 ; exit $ret
main.go
make: *** [goimports] Error 1

**Comment by scottjbarr** [comment]
Thanks @hayu-gpsw . Fixed.
