### ISSUE TITLE
Off-by-one error in outer waitgroup

### ISSUE THREAD

**Issue by DanielVango** [scottjbarr/sqsmv#32]
After completing, sqsmv panics with 

panic: sync: negative WaitGroup counter

```
goroutine 1 [running]:
sync.(*WaitGroup).Add(0x4cd4f8, 0xc0000120f0)
	/usr/local/go/src/sync/waitgroup.go:74 +0x105
sync.(*WaitGroup).Done(0x9)
	/usr/local/go/src/sync/waitgroup.go:99 +0x25
main.main()
	/go/src/app/main.go:59 +0x582
```

This appears to be due to an extraneous defer wg.Done() on [line 51](https://github.com/scottjbarr/sqsmv/blob/7ee5bace0b988b1b63440e46699b5e9ae2254664/main.go#L51)

Removing this line allows sqsmv to complete successfully without panicking

Addressed by https://github.com/scottjbarr/sqsmv/pull/33

**Comment by briantrice** [comment]
Thanks for catching the error in my PR!
