### ISSUE TITLE
Add links to Golang installation

### ISSUE THREAD

**Issue by rocheio** [scottjbarr/sqsmv#6]
Great tool - thanks for making this!

You might want to add some docs on the basic Go setup for non-gophers that want to use this tool. A link to https://golang.org/doc/install#install and a note about adding `export PATH=$PATH:$GOPATH/bin` to your `.bash_profile` in order to have the command immediately available would be super helpful.

Alternately I like the Docker setup provided in the PR by resilva: https://github.com/scottjbarr/sqsmv/pull/5 , but then you have a Docker dependency instead of a Go dependency

**Comment by scottjbarr** [comment]
I'm not keen to add a link to how to install Go, that can be found easily enough and different people like to install things different ways.

However to allow other to use the tool, I have created binary releases for Linux, Darwin and Windows. I've added a note to the [README](README) regarding this. I hope that helps :)

**Comment by rocheio** [comment]
Thanks again Scott, that's an even better solution. I appreciate it!
