### ISSUE TITLE
Moving between different accounts

### ISSUE THREAD

**Issue by fireboy1919** [scottjbarr/sqsmv#8]
A rather obvious use case for this is that you're accessing an SQS instance from a different region and different account.  In which case, using the same credentials for both queues isn't possible.

**Comment by scottjbarr** [comment]
In that case you could dequeue all messages to a local directory, then requeue all messages back up to another account.

Although your use case is valid, I don't see the value in complicating a relatively simple tool with multiple accounts. 

Maybe it could be worth adding dequeue to directory, and requeue from directory as options. You could dequeue as account A, and requeue as acocunt B. But this would need to not interfere with the way the common case works now.
