### ISSUE TITLE
sqsmv panics with 'no such host' error since ab52f23bf9c33252f9e81bce6d9109cc08f6b0eb

### ISSUE THREAD

**Issue by joelittlejohn** [scottjbarr/sqsmv#9]
When running _sqsmv_ from the latest HEAD (ab52f23bf9c33252f9e81bce6d9109cc08f6b0eb) like this:

```
sqsmv -src "https://eu-west-1.queue.amazonaws.com/15499999999/queue1" \
      -dest "https://eu-west-1.queue.amazonaws.com/15499999999/queue2"
``` 

I see the following error:

```
panic: RequestError: send request failed
caused by: Post https://sqs.queue.amazonaws.com/: dial tcp: lookup sqs.queue.amazonaws.com on 127.0.0.53:53: no such host

goroutine 1 [running]:
main.main()
	/home/jl/workspace/go/src/github.com/scottjbarr/sqsmv/main.go:44 +0x720
```

If I revert to d66ea8acccf2e46e03d959df90ca6c1a96cc5abe then everything works fine.

I have the following env vars set when running sqsmv:
```
AWS_DEFAULT_REGION="eu-west-1"
AWS_REGION="eu-west-1"
AWS_ACCESS_KEY_ID="AK..."
AWS_SECRET_ACCESS_KEY="..."
```

**Comment by scottjbarr** [comment]
Thanks @joelittlejohn 

I've reverted ab52f23, which was introduced by #7

**Comment by panga** [comment]
Please follow the instructions and unset AWS_DEFAULT_REGION and AWS_REGION, it should work.

**Comment by scottjbarr** [comment]
Yes, that is a fair point for an envionment that works with AWS tools. I have `AWS_REGION` set as well for use from my local machines.

**Comment by scottjbarr** [comment]
Closing
